import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({ url: "file:./dev.db" });
const prisma = new PrismaClient({ adapter } as never);

const DAYS = { SUN: 0, MON: 1, TUE: 2, WED: 3, THU: 4, FRI: 5, SAT: 6, DAILY: -1 };

async function main() {
  console.log("Seeding database...");

  // --- Tags ---
  const tagData = [
    { name: "Margaritas", category: "drink", icon: "🍹" },
    { name: "Draft Beer", category: "drink", icon: "🍺" },
    { name: "Craft Cocktails", category: "drink", icon: "🍸" },
    { name: "Wine", category: "drink", icon: "🍷" },
    { name: "Shots", category: "drink", icon: "🥃" },
    { name: "Frozen Drinks", category: "drink", icon: "🧃" },
    { name: "Tacos", category: "food", icon: "🌮" },
    { name: "Wings", category: "food", icon: "🍗" },
    { name: "Nachos", category: "food", icon: "🧀" },
    { name: "Burgers", category: "food", icon: "🍔" },
    { name: "Pizza", category: "food", icon: "🍕" },
    { name: "Sushi", category: "food", icon: "🍣" },
    { name: "Live Music", category: "vibe", icon: "🎸" },
    { name: "DJ", category: "vibe", icon: "🎧" },
    { name: "Trivia", category: "vibe", icon: "🧠" },
    { name: "Patio", category: "amenity", icon: "🌿" },
    { name: "Dog Friendly", category: "amenity", icon: "🐶" },
    { name: "Rooftop", category: "amenity", icon: "🏙️" },
    { name: "Sports TV", category: "amenity", icon: "📺" },
    { name: "Pool Tables", category: "amenity", icon: "🎱" },
    { name: "Mexican", category: "vibe", icon: "🇲🇽" },
    { name: "Karaoke", category: "vibe", icon: "🎤" },
    { name: "Board Games", category: "vibe", icon: "🎲" },
    { name: "Happy Hour Food", category: "food", icon: "🍽️" },
  ];

  const tags: Record<string, { id: string }> = {};
  for (const t of tagData) {
    const tag = await prisma.tag.upsert({
      where: { name: t.name },
      update: {},
      create: t,
    });
    tags[t.name] = tag;
  }

  // --- Restaurants ---
  const restaurants = [
    {
      name: "Rio Grande Cantina",
      slug: "rio-grande-cantina",
      address: "208 W 4th St",
      lat: 30.2686,
      lng: -97.7476,
      cuisine: "Mexican",
      priceRange: 2,
      phone: "(512) 555-0101",
      website: "https://example.com",
      description: "Austin's favorite Mexican bar with $4 margaritas daily and the best queso on 4th Street.",
      rating: 4.6,
      reviewCount: 843,
      verified: true,
      featured: true,
      tier: "premium",
      tags: ["Margaritas", "Tacos", "Nachos", "Patio", "Mexican", "Frozen Drinks"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "15:00",
          endTime: "18:00",
          label: "Happy Hour",
          items: [
            { name: "$4 House Margaritas", category: "cocktail", origPrice: 9, salePrice: 4 },
            { name: "$3 Lone Star", category: "beer", origPrice: 5, salePrice: 3 },
            { name: "$5 House Shots", category: "shot", origPrice: 7, salePrice: 5 },
            { name: "Half-Off Queso", category: "food", discount: "50% off" },
            { name: "Half-Off Nachos", category: "food", discount: "50% off" },
          ],
        },
      ],
    },
    {
      name: "The Rusty Nail",
      slug: "the-rusty-nail",
      address: "1117 S Congress Ave",
      lat: 30.2531,
      lng: -97.7503,
      cuisine: "American",
      priceRange: 2,
      phone: "(512) 555-0102",
      description: "A beloved South Congress dive bar with killer craft beers and some of Austin's cheapest pints.",
      rating: 4.4,
      reviewCount: 621,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Draft Beer", "Wings", "Sports TV", "Pool Tables", "Dog Friendly"],
      happyHours: [
        {
          dayOfWeek: DAYS.MON,
          startTime: "16:00",
          endTime: "19:00",
          label: "Monday Funday",
          items: [
            { name: "$2 Lone Stars", category: "beer", origPrice: 4, salePrice: 2 },
            { name: "$4 Well Drinks", category: "cocktail", origPrice: 7, salePrice: 4 },
            { name: "50¢ Wings", category: "food", description: "per wing, minimum 6", salePrice: 0.5 },
          ],
        },
        {
          dayOfWeek: DAYS.WED,
          startTime: "16:00",
          endTime: "19:00",
          label: "Hump Day Special",
          items: [
            { name: "$3 Draft Beers", category: "beer", origPrice: 6, salePrice: 3 },
            { name: "$4 Well Drinks", category: "cocktail", origPrice: 7, salePrice: 4 },
          ],
        },
        {
          dayOfWeek: DAYS.FRI,
          startTime: "15:00",
          endTime: "18:00",
          label: "TGIF Happy Hour",
          items: [
            { name: "$3 Domestics", category: "beer", origPrice: 5, salePrice: 3 },
            { name: "$5 Craft Beers", category: "beer", origPrice: 8, salePrice: 5 },
            { name: "$4 Well Drinks", category: "cocktail", origPrice: 7, salePrice: 4 },
          ],
        },
      ],
    },
    {
      name: "Loro Asian Smokehouse",
      slug: "loro-asian-smokehouse",
      address: "2115 S Lamar Blvd",
      lat: 30.2484,
      lng: -97.7665,
      cuisine: "Asian Fusion",
      priceRange: 3,
      phone: "(512) 555-0103",
      description: "Where Asian flavors meet Texas BBQ. James Beard award-winning team. Stunning patio.",
      rating: 4.8,
      reviewCount: 1204,
      verified: true,
      featured: true,
      tier: "premium",
      tags: ["Craft Cocktails", "Wine", "Patio", "Happy Hour Food"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "14:00",
          endTime: "17:00",
          label: "Afternoon Happy Hour",
          items: [
            { name: "Sake Bomb", category: "cocktail", origPrice: 12, salePrice: 8 },
            { name: "House Wine", category: "wine", origPrice: 10, salePrice: 7 },
            { name: "$5 Draft Beer", category: "beer", origPrice: 8, salePrice: 5 },
            { name: "Brisket Fried Rice", category: "food", description: "Happy hour exclusive", salePrice: 9 },
          ],
        },
      ],
    },
    {
      name: "Midnight Cowboy",
      slug: "midnight-cowboy",
      address: "313 E 6th St",
      lat: 30.2697,
      lng: -97.7388,
      cuisine: "Cocktail Bar",
      priceRange: 3,
      phone: "(512) 555-0104",
      description: "Award-winning speakeasy serving craft cocktails in an intimate reservation-only setting.",
      rating: 4.9,
      reviewCount: 532,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Shots"],
      happyHours: [
        {
          dayOfWeek: DAYS.TUE,
          startTime: "17:00",
          endTime: "20:00",
          label: "Cocktail Hour",
          items: [
            { name: "Classic Cocktails", category: "cocktail", origPrice: 16, salePrice: 10 },
            { name: "Seasonal Shots", category: "shot", origPrice: 8, salePrice: 5 },
          ],
        },
        {
          dayOfWeek: DAYS.THU,
          startTime: "17:00",
          endTime: "20:00",
          label: "Cocktail Hour",
          items: [
            { name: "Classic Cocktails", category: "cocktail", origPrice: 16, salePrice: 10 },
            { name: "Seasonal Shots", category: "shot", origPrice: 8, salePrice: 5 },
          ],
        },
      ],
    },
    {
      name: "Juan in a Million",
      slug: "juan-in-a-million",
      address: "2300 E Cesar Chavez St",
      lat: 30.2579,
      lng: -97.7198,
      cuisine: "Mexican",
      priceRange: 1,
      phone: "(512) 555-0105",
      description: "East Austin institution famous for massive breakfast tacos and $2 Modelo Especials.",
      rating: 4.7,
      reviewCount: 2341,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Margaritas", "Tacos", "Mexican", "Dog Friendly"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "16:00",
          endTime: "19:00",
          label: "Afternoon Especial",
          items: [
            { name: "$2 Modelos", category: "beer", origPrice: 4, salePrice: 2 },
            { name: "$5 House Margaritas", category: "cocktail", origPrice: 8, salePrice: 5 },
            { name: "Taco Specials", category: "food", description: "2 tacos for $5", salePrice: 5 },
          ],
        },
      ],
    },
    {
      name: "Fixe Southern House",
      slug: "fixe-southern-house",
      address: "500 W 5th St",
      lat: 30.2693,
      lng: -97.7482,
      cuisine: "Southern",
      priceRange: 3,
      phone: "(512) 555-0106",
      description: "Upscale Southern comfort food with an extensive whiskey bar and live jazz on weekends.",
      rating: 4.5,
      reviewCount: 789,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Wine", "Live Music", "Happy Hour Food"],
      happyHours: [
        {
          dayOfWeek: DAYS.MON,
          startTime: "17:00",
          endTime: "19:00",
          label: "Southern Sundown",
          items: [
            { name: "Whiskey Flights", category: "shot", origPrice: 18, salePrice: 12 },
            { name: "House Wine", category: "wine", origPrice: 11, salePrice: 7 },
            { name: "Deviled Eggs", category: "food", origPrice: 9, salePrice: 5 },
            { name: "Fried Chicken Bites", category: "food", origPrice: 13, salePrice: 8 },
          ],
        },
        {
          dayOfWeek: DAYS.TUE,
          startTime: "17:00",
          endTime: "19:00",
          label: "Southern Sundown",
          items: [
            { name: "Whiskey Flights", category: "shot", origPrice: 18, salePrice: 12 },
            { name: "House Wine", category: "wine", origPrice: 11, salePrice: 7 },
          ],
        },
        {
          dayOfWeek: DAYS.WED,
          startTime: "17:00",
          endTime: "19:00",
          label: "Southern Sundown",
          items: [
            { name: "Whiskey Flights", category: "shot", origPrice: 18, salePrice: 12 },
            { name: "House Wine", category: "wine", origPrice: 11, salePrice: 7 },
          ],
        },
      ],
    },
    {
      name: "The Hole In The Wall",
      slug: "the-hole-in-the-wall",
      address: "2538 Guadalupe St",
      lat: 30.2912,
      lng: -97.7408,
      cuisine: "Dive Bar",
      priceRange: 1,
      phone: "(512) 555-0107",
      description: "Austin's most iconic dive bar since 1974. Cheap beer, live music, and zero pretension.",
      rating: 4.3,
      reviewCount: 1876,
      verified: true,
      featured: false,
      tier: "free",
      tags: ["Draft Beer", "Live Music", "Pool Tables", "Dog Friendly"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "11:00",
          endTime: "20:00",
          label: "All Day Happy Hour",
          items: [
            { name: "$2 Lone Stars", category: "beer", origPrice: 3, salePrice: 2 },
            { name: "$3 Well Drinks", category: "cocktail", origPrice: 5, salePrice: 3 },
            { name: "$3 PBR Tall Boys", category: "beer", origPrice: 4, salePrice: 3 },
          ],
        },
      ],
    },
    {
      name: "Uchi",
      slug: "uchi",
      address: "801 S Lamar Blvd",
      lat: 30.2575,
      lng: -97.7648,
      cuisine: "Japanese",
      priceRange: 4,
      phone: "(512) 555-0108",
      description: "James Beard Award-winning Japanese restaurant. Late Night Happy Hour is one of Austin's best kept secrets.",
      rating: 4.9,
      reviewCount: 3201,
      verified: true,
      featured: true,
      tier: "premium",
      tags: ["Sushi", "Craft Cocktails", "Wine", "Happy Hour Food"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "22:00",
          endTime: "23:30",
          label: "Late Night Happy Hour",
          items: [
            { name: "Select Nigiri", category: "food", description: "Chef's selection", origPrice: 8, salePrice: 4 },
            { name: "Maki Rolls", category: "food", origPrice: 14, salePrice: 7 },
            { name: "Sake by the Glass", category: "cocktail", origPrice: 14, salePrice: 8 },
            { name: "Japanese Whiskey", category: "shot", origPrice: 18, salePrice: 10 },
          ],
        },
      ],
    },
    {
      name: "Easy Tiger",
      slug: "easy-tiger",
      address: "709 E 6th St",
      lat: 30.2668,
      lng: -97.7363,
      cuisine: "Beer Garden",
      priceRange: 2,
      phone: "(512) 555-0109",
      description: "Craft bakery and beer garden on Waller Creek. Best outdoor happy hour in Austin.",
      rating: 4.6,
      reviewCount: 1654,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Draft Beer", "Craft Cocktails", "Patio", "Dog Friendly", "Nachos"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "15:00",
          endTime: "18:00",
          label: "Creekside Happy Hour",
          items: [
            { name: "$5 Rotating Draft", category: "beer", origPrice: 8, salePrice: 5 },
            { name: "House Cocktails", category: "cocktail", origPrice: 12, salePrice: 8 },
            { name: "Fresh Pretzels", category: "food", origPrice: 7, salePrice: 4 },
          ],
        },
      ],
    },
    {
      name: "Contigo",
      slug: "contigo",
      address: "2027 Anchor Ln",
      lat: 30.2978,
      lng: -97.7102,
      cuisine: "American",
      priceRange: 3,
      phone: "(512) 555-0110",
      description: "Farm-to-table neighborhood bar and restaurant with a stunning covered patio and great cocktails.",
      rating: 4.5,
      reviewCount: 934,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Wine", "Patio", "Dog Friendly", "Happy Hour Food"],
      happyHours: [
        {
          dayOfWeek: DAYS.MON,
          startTime: "17:00",
          endTime: "19:00",
          label: "Neighborhood Happy Hour",
          items: [
            { name: "Glass of Wine", category: "wine", origPrice: 12, salePrice: 7 },
            { name: "Seasonal Cocktail", category: "cocktail", origPrice: 13, salePrice: 8 },
            { name: "Deviled Eggs", category: "food", origPrice: 8, salePrice: 5 },
          ],
        },
        {
          dayOfWeek: DAYS.TUE,
          startTime: "17:00",
          endTime: "19:00",
          label: "Neighborhood Happy Hour",
          items: [
            { name: "Glass of Wine", category: "wine", origPrice: 12, salePrice: 7 },
            { name: "Seasonal Cocktail", category: "cocktail", origPrice: 13, salePrice: 8 },
          ],
        },
        {
          dayOfWeek: DAYS.WED,
          startTime: "17:00",
          endTime: "19:00",
          label: "Neighborhood Happy Hour",
          items: [
            { name: "Glass of Wine", category: "wine", origPrice: 12, salePrice: 7 },
            { name: "Seasonal Cocktail", category: "cocktail", origPrice: 13, salePrice: 8 },
          ],
        },
        {
          dayOfWeek: DAYS.THU,
          startTime: "17:00",
          endTime: "19:00",
          label: "Neighborhood Happy Hour",
          items: [
            { name: "Glass of Wine", category: "wine", origPrice: 12, salePrice: 7 },
            { name: "Seasonal Cocktail", category: "cocktail", origPrice: 13, salePrice: 8 },
          ],
        },
        {
          dayOfWeek: DAYS.FRI,
          startTime: "17:00",
          endTime: "19:00",
          label: "Neighborhood Happy Hour",
          items: [
            { name: "Glass of Wine", category: "wine", origPrice: 12, salePrice: 7 },
            { name: "Seasonal Cocktail", category: "cocktail", origPrice: 13, salePrice: 8 },
          ],
        },
      ],
    },
    {
      name: "Rainey Street Social",
      slug: "rainey-street-social",
      address: "86 Rainey St",
      lat: 30.2587,
      lng: -97.7416,
      cuisine: "Bar",
      priceRange: 2,
      phone: "(512) 555-0111",
      description: "The heart of Rainey Street. Great cocktails, killer patio, and the best sunset views in Austin.",
      rating: 4.4,
      reviewCount: 1123,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Draft Beer", "Patio", "DJ", "Rooftop"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "16:00",
          endTime: "19:00",
          label: "Rainey Hour",
          items: [
            { name: "$6 Signature Cocktails", category: "cocktail", origPrice: 11, salePrice: 6 },
            { name: "$4 Draft Beers", category: "beer", origPrice: 7, salePrice: 4 },
            { name: "$4 House Wine", category: "wine", origPrice: 9, salePrice: 4 },
          ],
        },
      ],
    },
    {
      name: "Garage Cocktail Bar",
      slug: "garage-cocktail-bar",
      address: "503 Colorado St",
      lat: 30.2676,
      lng: -97.7449,
      cuisine: "Cocktail Bar",
      priceRange: 3,
      phone: "(512) 555-0112",
      description: "Chic cocktail bar in a restored parking garage. Creative drinks, stunning multi-level space.",
      rating: 4.7,
      reviewCount: 876,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Wine", "Rooftop"],
      happyHours: [
        {
          dayOfWeek: DAYS.MON,
          startTime: "17:00",
          endTime: "20:00",
          label: "Happy Hour",
          items: [
            { name: "Classic Cocktails", category: "cocktail", origPrice: 14, salePrice: 9 },
            { name: "House Wine", category: "wine", origPrice: 10, salePrice: 6 },
            { name: "Draft Beer", category: "beer", origPrice: 8, salePrice: 5 },
          ],
        },
        {
          dayOfWeek: DAYS.TUE,
          startTime: "17:00",
          endTime: "20:00",
          label: "Happy Hour",
          items: [
            { name: "Classic Cocktails", category: "cocktail", origPrice: 14, salePrice: 9 },
            { name: "House Wine", category: "wine", origPrice: 10, salePrice: 6 },
          ],
        },
        {
          dayOfWeek: DAYS.WED,
          startTime: "17:00",
          endTime: "20:00",
          label: "Happy Hour",
          items: [
            { name: "Classic Cocktails", category: "cocktail", origPrice: 14, salePrice: 9 },
            { name: "House Wine", category: "wine", origPrice: 10, salePrice: 6 },
          ],
        },
        {
          dayOfWeek: DAYS.THU,
          startTime: "17:00",
          endTime: "20:00",
          label: "Happy Hour",
          items: [
            { name: "Classic Cocktails", category: "cocktail", origPrice: 14, salePrice: 9 },
            { name: "House Wine", category: "wine", origPrice: 10, salePrice: 6 },
          ],
        },
        {
          dayOfWeek: DAYS.FRI,
          startTime: "16:00",
          endTime: "19:00",
          label: "Friday Happy Hour",
          items: [
            { name: "Classic Cocktails", category: "cocktail", origPrice: 14, salePrice: 9 },
            { name: "Prosecco", category: "wine", origPrice: 12, salePrice: 7 },
          ],
        },
      ],
    },
    {
      name: "Stubb's Waller Creek Amphitheater",
      slug: "stubbs-bbq",
      address: "801 Red River St",
      lat: 30.2663,
      lng: -97.7334,
      cuisine: "BBQ",
      priceRange: 2,
      phone: "(512) 555-0113",
      description: "Legendary outdoor music venue and BBQ joint. Where Austin's soul lives.",
      rating: 4.8,
      reviewCount: 4512,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Draft Beer", "Live Music", "Patio"],
      happyHours: [
        {
          dayOfWeek: DAYS.WED,
          startTime: "16:00",
          endTime: "18:00",
          label: "Waller Creek Social",
          items: [
            { name: "$3 Lone Stars", category: "beer", origPrice: 5, salePrice: 3 },
            { name: "$4 Well Drinks", category: "cocktail", origPrice: 6, salePrice: 4 },
            { name: "BBQ Plate Deal", category: "food", description: "Brisket + 2 sides", origPrice: 18, salePrice: 12 },
          ],
        },
      ],
    },
    {
      name: "Péché",
      slug: "peche",
      address: "208 W 4th St",
      lat: 30.2687,
      lng: -97.7478,
      cuisine: "French",
      priceRange: 3,
      phone: "(512) 555-0114",
      description: "Parisian-inspired absinthe bar with French small plates and an encyclopedic spirits list.",
      rating: 4.6,
      reviewCount: 543,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Wine", "Happy Hour Food"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "17:00",
          endTime: "19:00",
          label: "L'Heure Verte",
          items: [
            { name: "Absinthe Drip", category: "shot", origPrice: 14, salePrice: 8 },
            { name: "French 75", category: "cocktail", origPrice: 14, salePrice: 9 },
            { name: "Cheese Plate", category: "food", origPrice: 16, salePrice: 10 },
            { name: "House Wine", category: "wine", origPrice: 10, salePrice: 6 },
          ],
        },
      ],
    },
    {
      name: "Bouldin Creek Cafe",
      slug: "bouldin-creek-cafe",
      address: "1900 S 1st St",
      lat: 30.2484,
      lng: -97.7573,
      cuisine: "Vegetarian",
      priceRange: 1,
      phone: "(512) 555-0115",
      description: "Funky vegetarian cafe with a cozy patio and excellent cocktails. Come for the vibe, stay for the migas.",
      rating: 4.5,
      reviewCount: 1432,
      verified: true,
      featured: false,
      tier: "free",
      tags: ["Craft Cocktails", "Wine", "Patio", "Dog Friendly"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "16:00",
          endTime: "18:00",
          label: "Afternoon Happy Hour",
          items: [
            { name: "$6 House Cocktails", category: "cocktail", origPrice: 9, salePrice: 6 },
            { name: "$5 Wine", category: "wine", origPrice: 8, salePrice: 5 },
            { name: "$3 PBR", category: "beer", origPrice: 4, salePrice: 3 },
          ],
        },
      ],
    },
    {
      name: "Olamaie",
      slug: "olamaie",
      address: "1610 San Antonio St",
      lat: 30.2831,
      lng: -97.7461,
      cuisine: "Southern",
      priceRange: 4,
      phone: "(512) 555-0116",
      description: "James Beard nominated Southern fine dining. Known for legendary biscuits and sophisticated cocktails.",
      rating: 4.8,
      reviewCount: 678,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Wine", "Happy Hour Food"],
      happyHours: [
        {
          dayOfWeek: DAYS.TUE,
          startTime: "17:00",
          endTime: "18:30",
          label: "Pre-Dinner Special",
          items: [
            { name: "Biscuits with Honey Butter", category: "food", description: "Complimentary with bar seating", salePrice: 0 },
            { name: "Cocktail of the Week", category: "cocktail", origPrice: 15, salePrice: 10 },
            { name: "House Wine", category: "wine", origPrice: 13, salePrice: 8 },
          ],
        },
        {
          dayOfWeek: DAYS.WED,
          startTime: "17:00",
          endTime: "18:30",
          label: "Pre-Dinner Special",
          items: [
            { name: "Biscuits with Honey Butter", category: "food", description: "Complimentary with bar seating", salePrice: 0 },
            { name: "Cocktail of the Week", category: "cocktail", origPrice: 15, salePrice: 10 },
            { name: "House Wine", category: "wine", origPrice: 13, salePrice: 8 },
          ],
        },
        {
          dayOfWeek: DAYS.THU,
          startTime: "17:00",
          endTime: "18:30",
          label: "Pre-Dinner Special",
          items: [
            { name: "Biscuits with Honey Butter", category: "food", description: "Complimentary with bar seating", salePrice: 0 },
            { name: "Cocktail of the Week", category: "cocktail", origPrice: 15, salePrice: 10 },
            { name: "House Wine", category: "wine", origPrice: 13, salePrice: 8 },
          ],
        },
      ],
    },
    {
      name: "Whisler's",
      slug: "whislers",
      address: "1816 E 6th St",
      lat: 30.2624,
      lng: -97.7224,
      cuisine: "Cocktail Bar",
      priceRange: 3,
      phone: "(512) 555-0117",
      description: "East 6th's beloved cocktail den with an extensive mezcal selection and a rooftop mezcaleria.",
      rating: 4.7,
      reviewCount: 987,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Shots", "Rooftop", "Mexican"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "17:00",
          endTime: "20:00",
          label: "Mezcal Hour",
          items: [
            { name: "$7 Mezcal Cocktails", category: "cocktail", origPrice: 13, salePrice: 7 },
            { name: "$5 Mezcal Shots", category: "shot", origPrice: 10, salePrice: 5 },
            { name: "$4 Tecate", category: "beer", origPrice: 6, salePrice: 4 },
          ],
        },
      ],
    },
    {
      name: "The ABGB",
      slug: "the-abgb",
      address: "1305 W Oltorf St",
      lat: 30.2403,
      lng: -97.7621,
      cuisine: "Brewery",
      priceRange: 2,
      phone: "(512) 555-0118",
      description: "Austin Beer Garden Brewing — craft brewery with live music and a killer backyard. Their pizza is legendary.",
      rating: 4.6,
      reviewCount: 1543,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Draft Beer", "Live Music", "Patio", "Pizza", "Dog Friendly"],
      happyHours: [
        {
          dayOfWeek: DAYS.DAILY,
          startTime: "14:00",
          endTime: "17:00",
          label: "Brewer's Happy Hour",
          items: [
            { name: "$4 House Drafts", category: "beer", origPrice: 7, salePrice: 4 },
            { name: "$3 PBR / Lone Star", category: "beer", origPrice: 5, salePrice: 3 },
            { name: "$2 Off Pizzas", category: "food", discount: "$2 off any pizza" },
          ],
        },
      ],
    },
    {
      name: "Salty Sow",
      slug: "salty-sow",
      address: "1917 Manor Rd",
      lat: 30.2798,
      lng: -97.7114,
      cuisine: "American",
      priceRange: 3,
      phone: "(512) 555-0119",
      description: "Craft cocktails, elevated pub food, and the best duck fat fries in Austin. East Austin staple.",
      rating: 4.5,
      reviewCount: 876,
      verified: true,
      featured: false,
      tier: "standard",
      tags: ["Craft Cocktails", "Draft Beer", "Happy Hour Food"],
      happyHours: [
        {
          dayOfWeek: DAYS.MON,
          startTime: "17:00",
          endTime: "19:00",
          label: "Sow's Happy Hour",
          items: [
            { name: "House Cocktails", category: "cocktail", origPrice: 12, salePrice: 7 },
            { name: "Draft Beer", category: "beer", origPrice: 7, salePrice: 4 },
            { name: "Duck Fat Fries", category: "food", origPrice: 10, salePrice: 6 },
          ],
        },
        {
          dayOfWeek: DAYS.TUE,
          startTime: "17:00",
          endTime: "19:00",
          label: "Sow's Happy Hour",
          items: [
            { name: "House Cocktails", category: "cocktail", origPrice: 12, salePrice: 7 },
            { name: "Draft Beer", category: "beer", origPrice: 7, salePrice: 4 },
          ],
        },
        {
          dayOfWeek: DAYS.WED,
          startTime: "17:00",
          endTime: "19:00",
          label: "Sow's Happy Hour",
          items: [
            { name: "House Cocktails", category: "cocktail", origPrice: 12, salePrice: 7 },
            { name: "Draft Beer", category: "beer", origPrice: 7, salePrice: 4 },
          ],
        },
        {
          dayOfWeek: DAYS.THU,
          startTime: "17:00",
          endTime: "19:00",
          label: "Sow's Happy Hour",
          items: [
            { name: "House Cocktails", category: "cocktail", origPrice: 12, salePrice: 7 },
            { name: "Draft Beer", category: "beer", origPrice: 7, salePrice: 4 },
          ],
        },
        {
          dayOfWeek: DAYS.FRI,
          startTime: "15:00",
          endTime: "18:00",
          label: "TGIF at Salty Sow",
          items: [
            { name: "House Cocktails", category: "cocktail", origPrice: 12, salePrice: 7 },
            { name: "Prosecco by the Glass", category: "wine", origPrice: 11, salePrice: 6 },
          ],
        },
      ],
    },
    {
      name: "La Condesa",
      slug: "la-condesa",
      address: "400 W 2nd St",
      lat: 30.2661,
      lng: -97.7473,
      cuisine: "Mexican",
      priceRange: 3,
      phone: "(512) 555-0120",
      description: "Sophisticated modern Mexican in the heart of downtown. James Beard nominated, exceptional mezcal list.",
      rating: 4.6,
      reviewCount: 2108,
      verified: true,
      featured: true,
      tier: "premium",
      tags: ["Margaritas", "Craft Cocktails", "Tacos", "Mexican", "Happy Hour Food"],
      happyHours: [
        {
          dayOfWeek: DAYS.MON,
          startTime: "16:00",
          endTime: "18:00",
          label: "La Hora Feliz",
          items: [
            { name: "$8 Margaritas", category: "cocktail", origPrice: 14, salePrice: 8 },
            { name: "$6 Mezcal", category: "shot", origPrice: 12, salePrice: 6 },
            { name: "Guacamole + Chips", category: "food", origPrice: 12, salePrice: 7 },
            { name: "Street Tacos (3)", category: "food", origPrice: 14, salePrice: 9 },
          ],
        },
        {
          dayOfWeek: DAYS.TUE,
          startTime: "16:00",
          endTime: "18:00",
          label: "La Hora Feliz",
          items: [
            { name: "$8 Margaritas", category: "cocktail", origPrice: 14, salePrice: 8 },
            { name: "$6 Mezcal", category: "shot", origPrice: 12, salePrice: 6 },
            { name: "Guacamole + Chips", category: "food", origPrice: 12, salePrice: 7 },
          ],
        },
        {
          dayOfWeek: DAYS.WED,
          startTime: "16:00",
          endTime: "18:00",
          label: "La Hora Feliz",
          items: [
            { name: "$8 Margaritas", category: "cocktail", origPrice: 14, salePrice: 8 },
            { name: "$6 Mezcal", category: "shot", origPrice: 12, salePrice: 6 },
          ],
        },
        {
          dayOfWeek: DAYS.THU,
          startTime: "16:00",
          endTime: "18:00",
          label: "La Hora Feliz",
          items: [
            { name: "$8 Margaritas", category: "cocktail", origPrice: 14, salePrice: 8 },
            { name: "$6 Mezcal", category: "shot", origPrice: 12, salePrice: 6 },
          ],
        },
        {
          dayOfWeek: DAYS.FRI,
          startTime: "16:00",
          endTime: "18:00",
          label: "La Hora Feliz",
          items: [
            { name: "$8 Margaritas", category: "cocktail", origPrice: 14, salePrice: 8 },
            { name: "$6 Mezcal", category: "shot", origPrice: 12, salePrice: 6 },
          ],
        },
      ],
    },
  ];

  for (const r of restaurants) {
    const { tags: tagNames, happyHours, ...restData } = r;
    const restaurant = await prisma.restaurant.upsert({
      where: { slug: restData.slug },
      update: {},
      create: restData,
    });

    for (const tagName of tagNames) {
      if (tags[tagName]) {
        await prisma.restaurantTag.upsert({
          where: { restaurantId_tagId: { restaurantId: restaurant.id, tagId: tags[tagName].id } },
          update: {},
          create: { restaurantId: restaurant.id, tagId: tags[tagName].id },
        });
      }
    }

    for (const hh of happyHours) {
      const { items, ...hhData } = hh;
      const happyHour = await prisma.happyHour.create({
        data: { ...hhData, restaurantId: restaurant.id },
      });
      for (const item of items) {
        await prisma.hHItem.create({
          data: { ...item, happyHourId: happyHour.id },
        });
      }
    }
  }

  console.log(`Seeded ${restaurants.length} restaurants with happy hours and tags.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
